version: '3.7'

services:
  db:
    image: postgres
  cnab_parser:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/cnab_parser
      - gems:/gems
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  gems:
