default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: admin
  pool: 5

development:
  <<: *default
  database: cnab_parser_development

test:
  <<: *default
  database: cnab_parser_test
