source 'https://rubygems.org' do
  group :test do
    gem 'rack-test'
    gem 'rspec'
    gem 'rubocop-rspec'
  end

  gem 'interactor'
  gem 'pry-byebug'
  gem 'pg'
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'unicorn'
  gem 'activerecord'
  gem 'sinatra-activerecord'
  gem 'rake'
end
